version: "3.9"

services:
  back-end:
    depends_on:
      - db
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./back-end
    container_name: back-end
    environment:
      PORT: ${PORT}
      DB_URI: mongodb://${HOST_IP}:${MONGO_PORT}
      DB_USERNAME: ${MONGO_USERNAME}
      DB_PASSWORD: ${MONGO_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./back-end:/app
    logging:
      driver: "json-file"

  db:
    image: mongo
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - ${MONGO_PORT}:27017
    command: mongod --auth
    volumes:
      - /mongo/data:/data
      - /mongo/data/db:/data/db
      - /mongo/data/configdb:/data/configdb
    logging:
      driver: "json-file"
